kind: Secret
apiVersion: v1
metadata:
  name: barauth-empty
  namespace: cp4i
data:
  configuration: >-
    eyJhdXRoVHlwZSI6IkJBU0lDX0FVVEgiLCJjcmVkZW50aWFscyI6eyJ1c2VybmFtZSI6IiIsInBhc3N3b3JkIjoiIn19Cg==
type: Opaque
